name: 'AWS Application Secrets'
description: 'Provides AWS application secrets'
inputs:
  project-name:
    description: Project name. Defaults to PROJECT_NAME from environment variable.
    required: false
  environment:
    description: Environment (staging/production). Defaults to ENVIRONMENT environment variable.
    required: false
  type:
    description: Parameter Type (BUILD, RUNTIME, ALL)
    required: false
    default: BUILD
runs:
  using: 'node24'
  main: '../../dist/secrets.js'
