name: Trigger Deployment
description: 'Trigger an application deployment by dispatching an event to `cru-deploy` repo.'
inputs:
  project-name:
    description: Project name.
    required: true
  environment:
    description: Environment (staging/production/lab).
    required: true
  build-number:
    description: Build number.
    required: true
  github-token:
    description: The GitHub token used to create a workflow_dispatch event.
    required: true
  project:
    description: GCP Project ID. Required for `cloudrun`
    required: false
  deploy-type:
    description: Type of deployment ('ecs', 'lambda', 'cloudrun'). Defaults to 'ecs'.
    required: false
    default: 'ecs'
  workflow-ref:
    description: Branch, tag or commit used when calling the workflow. Required if calling the workflow from non default 'main' branch.
    required: false
    default: 'main'
runs:
  using: 'node24'
  main: '../../dist/trigger-deploy.js'
