name: Trigger Deployment
description: 'Trigger an application deployment by dispatching an event to `cru-deploy` repo.'
inputs:
  project-name:
    description: Project name.
    required: true
  environment:
    description: Environment (staging/production/lab).
    required: true
  build-number:
    description: Build number.
    required: true
  github-token:
    description: The GitHub token used to create a workflow_dispatch event.
    required: true
runs:
  using: 'node20'
  main: '../../dist/trigger-deploy.js'
