name: Build & Deploy Cloudrun Functions

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'function-name/**'
  workflow_dispatch:
    inputs:
      function_name:
        description: 'The name of the Cloud Function to deploy'
        required: true
        default: 'function-name'

jobs:
  build_and_deploy:

    uses: CruGlobal/.github/.github/workflows/build-deploy-cloudrun-function.yml@gcp-cloudrun #temporarily using branch for testing
    with:
      function_name: ${{ github.event.inputs.function_name }}
      entry_point: hello_http
      runtime: python312
      environment: production
