name: Build & Deploy ECS

on:
  push:
    branches:
      - $default-branch
      - staging
  workflow_dispatch:
    inputs:
      auto-deploy:
        type: boolean
        description: Deploy image after building?
        required: true
        default: 'false'

jobs:
  build:
    name: Build
    uses: CruGlobal/.github/.github/workflows/build-ecs.yml@v1
