name: Build

on:
  push:
    branches:
      - $default-branch
  workflow_dispatch:
    inputs:
      auto-deploy:
        type: boolean
        description: Deploy image after building?
        required: true
        default: 'false'

jobs:
  build:
    uses: CruGlobal/.github/.github/workflows/build-ecs.yml@v1

  deploy:
    uses: CruGlobal/.github/.github/workflows/deploy-ecs.yml@v1
    needs: build
    if: ${{ github.event_name == 'push' || github.events.inputs.auto-deploy == 'true' }}
    with:
      project-name: ${{ needs.build.outputs.project-name }}
      environment: ${{ needs.build.outputs.environment }}
      build-number: ${{ needs.build.outputs.build-number }}
