name: Setup ENV
description: Setup environment
inputs:
  project-name:
    description: Project Name, defaults to GitHub repo name.
    required: false
  environment:
    description: Environment, either staging or production
    required: false
  role-suffix:
    description: Suffix for the AWS IAM Role ARN, defaults to 'TaskRole'
    required: false
    default: 'TaskRole'

outputs:
  project-name:
    description: Project name
  environment:
    description: Environment
  role-arn:
    description: AWS IAM Role ARN to be assumed by GitHub to build/deploy the project.
runs:
  using: 'node20'
  main: '../../dist/setup-env.js'
