name: AEM Cloud Repository Sync

on:
  workflow_call:
    inputs:
      cloud-repository-name:
        description: Cloud Repository Name
        required: true
        type: string
      user-email:
        description: User Email
        required: true
        type: string
      user-name:
        description: User Name
        required: true
        type: string
      aem-cloud-branch-name:
        description: Branch Name
        required: true
        type: string
      update-submodules:
        description: Update submodules directive
        required: false
        type: boolean
        default: true
      git-push-command-line-options:
        description: git push command line options
        required: false
        type: string
        default: '--force'

    secrets:
      cloud-repository-username:
        description: Cloud Repository User Name
        required: true
      cloud-repository-password:
        description: Cloud Repository Password
        required: true
      aem-repository-github-api-token:
        description: Cloud Repository Personal Access Token
        required: true

jobs:
  # Running jobs directly on the runner machine
  aem-cloud-repo-sync:
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    steps:
      - uses: actions/checkout@v7

      - name: set git config
        env:
          USER_EMAIL: ${{ inputs.user-email }}
          USER_NAME: ${{ inputs.user-name }}
        run: |
            git config --global credential.helper cache
            git config --global user.email $USER_EMAIL
            git config --global user.name $USER_NAME

      - name: sync to aem cloud git repository
        env:
          CLOUD_REPOSITORY_USERNAME: ${{ secrets.cloud-repository-username }}
          CLOUD_REPOSITORY_PASSWORD: ${{ secrets.cloud-repository-password }}
          CLOUD_REPOSITORY_NAME: ${{ inputs.cloud-repository-name }}
          AEM_CLOUD_BRANCH_NAME: ${{ inputs.aem-cloud-branch-name }}
          PUSH_OPTIONS: ${{ inputs.git-push-command-line-options }}
        run: |
            git fetch --unshallow origin
            git push https://$CLOUD_REPOSITORY_USERNAME:$CLOUD_REPOSITORY_PASSWORD@git.cloudmanager.adobe.com/cru/$CLOUD_REPOSITORY_NAME $AEM_CLOUD_BRANCH_NAME $PUSH_OPTIONS

      - name: update CruGlobal aem-cloud submodules
        if: ${{ inputs.update-submodules }}
        env:
          AEM_REPOSITORY_GITHUB_API_TOKEN: ${{ secrets.aem-repository-github-api-token }}
          AEM_CLOUD_BRANCH_NAME: ${{ inputs.aem-cloud-branch-name }}
        run: |
            git clone https://user:$AEM_REPOSITORY_GITHUB_API_TOKEN@github.com/CruGlobal/aem-cloud.git
            cd aem-cloud
            git fetch origin $AEM_CLOUD_BRANCH_NAME
            git checkout $AEM_CLOUD_BRANCH_NAME
            git submodule update --init --recursive
            git submodule update --remote
            git add .
            git commit -m 'submodule update'
            git push origin $AEM_CLOUD_BRANCH_NAME
