name: Build and Deploy Cloud Run Function

on:
  push:
    branches:
      - $default-branch
      - staging
  workflow_call:
    inputs:
      function_name:
        description: 'The name of the Cloud Function to deploy'
        type: string
        required: true
    secrets:
      WORKLOAD_IDENTITY_PROVIDER:
        description: 'Workload Identity Provider'
        required: true
      GCP_SERVICE_ACCOUNT:
        description: 'GCP Service Account Name'
        required: true
      GCP_SERVICE_ACCOUNT_EMAIL:
        description: 'GCP Service Account Email'
        required: true
      RUN_SERVICE_ACCOUNT:
        description: 'Run Service Account'
        required: true
      GCP_PROJECT_ID:
        description: 'GCP Project ID'
        required: true
      GCP_REGION:
        description: 'GCP Region'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run Functions
        id: deploy
        env:
          GCP_REGION: ${{ secrets.GCP_REGION }}
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud functions deploy ${{ inputs.function_name }}-function \
            --region $GCP_REGION \
            --source=./${{ inputs.function_name }} \
            --build-service-account=projects/${{ secrets.GCP_PROJECT_ID }}/serviceAccounts/${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }} \

      - uses: actions/github-script@v6
        if: github.event.pull_request.merged == true
        with:
          script: |
            const output = `#### GCF Deploy ⚙️\`${{ steps.deploy.outcome }}\`
            <details><summary>Show Deploy</summary>
            \`\`\`\n
            ${{ steps.deploy.outputs.stdout }}
            \`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ inputs.function_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output