name: Create Release
# Read release notes from pr and create version from tag
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Extract Release Notes
        id: release-notes
        uses: actions/github-script@v6
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        with:
          script: |
            const body = process.env.PR_BODY;
            const regex = /<!-- #release_notes -->\n?(.*)<!-- \/release_notes -->/s
            const match = body.match(regex) ?? [];
            core.setOutput("notes", match[1])
      - name: Create release on GitHub
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.tag }}
          body: ${{ steps.release-notes.outputs.notes }}
          token: ${{ secrets.GITHUB_TOKEN }}
