name: Deploy to ECS

on:
  workflow_call:
    inputs:
      workflow-ref:
        type: string
        required: false
        default: main
        description: >-
          Branch, tag or commit used when calling the workflow.
          Required if calling the workflow from non default 'main' branch.
      project-name:
        description: Project Name
        required: true
        type: string
      environment:
        description: Environment (staging / production)
        required: true
        type: string
      build-number:
        description: ECS build number
        required: true
        type: string

jobs:
  deploy:
    name: Update ECS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout Cru Actions & Workflows
        uses: actions/checkout@v2
        with:
          repository: CruGlobal/.github
          ref: ${{ inputs.workflow-ref }}
          path: cru-github-actions

      - name: Setup Build environment
        uses: ./cru-github-actions/actions/setup-env
        id: env
        with:
          project-name: ${{ inputs.project-name }}
          environment: ${{ inputs.environment }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::056154071827:role/GitHubDeployECS

      - name: Update and register Task Definition
        uses: ./cru-github-actions/actions/deploy-ecs
