name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Update Release Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sersoft-gmbh/running-release-tags-action@v3
        with:
          tag: v1.3.0
          update-minor: false
          create-release: false
